### ISSUE TITLE
Cannot craft `techage:ta4_silicon_wafer` with `mesecons_materials:silicon`

### ISSUE THREAD

**Issue by nadiamoe** [joe7575/techage_modepack#11]
Hey,

Not sure if this is an issue or some kind of stupid player mistake. Please feel free to close if it's the second 😅 

I don't seem to be able to craft a `techage:ta4_silicon_wafer` on the TA3 industrial furnace. When I toss in 3 chunks of `mesecons_materials:silicon` and one `techage:baborium_ingot`, no recipes show up in the UI and I get a "Recipe error" if I try to turn the thing on manually.

From what I can read in the basic_materials code, `basic_materials:silicon` should be an alias of `mesecons_materials:silicon`, but I don't think that's fully working on my server. I cannot see Techage recipes on the `mesecons_materials:silicon`, and I can `/give` me `basic_materials:silicon` which gives me a different item with a slightly different texture.

![screenshot_20220926_002332](https://user-images.githubusercontent.com/969721/192168215-8efade5a-43c4-42ca-8d09-49b2f36784b4.png)

Could this be some kind of weird misconfiguration at my side?

**Comment by joe7575** [comment]
Do you see the recipe in the unifiedinventory crafting grid?

Perhaps a change in the mod load order could help. You could try to make `techage` dependent on `mesecons_materials`, or the other way around?

If this not helps, could you try to add an alternative recipe somewhere in a server related mod, which depends on techage:
```lua
techage.furnace.register_recipe({
	output = "techage:ta4_silicon_wafer 16",
	recipe = {
		"mesecons_materials:silicon",
		"mesecons_materials:silicon",
		"mesecons_materials:silicon",
		"techage:baborium_ingot"
	},
	time = 6,
})
```
If this is the solution, I could add this alternative recipe.

**Comment by nadiamoe** [comment]
> Do you see the recipe in the unifiedinventory crafting grid?

I don't, I see how to craft `mesecons_materials:silicon` with 3 sands and 1 steel ingot, but unifiedinventory shows no way to craft `basic_materials:silicon`.

> Perhaps a change in the mod load order could help. You could try to make `techage` dependent on `mesecons_materials`, or the other way around?

This is a good point, being a minetest noob I didn't know this was possible. I'll check right away :)

**Comment by nadiamoe** [comment]
Hey @joe7575,

I fixed the issue on my end making `basic_materials` optionally dependent on `mesecons_materials`. As `techage` already depends on `basic_materials`, I think making techage optionally depend on `mesecons_materials` would also work as well.

Seems like no extra recipe is needed :)

I'm not closing this right away in case you want to incorporate this fix upstream.

Thanks a lot for the pointer!

**Comment by joe7575** [comment]
I will add the optional dependency, thanks for testing this.
