### ISSUE TITLE
Use of deprecated field name in some tile definitions

### ISSUE THREAD

**Issue by RodentOfUnusualSize** [joe7575/techage_modepack#12]
Greetings, Earthling!

I was trying to use [minetestmapper](https://github.com/minetest/minetestmapper) with TechAge—specifically, I was trying to use the [`dumpnodes` mod](https://github.com/minetest/minetestmapper/tree/master/util/dumpnodes) to generate the colours file for the mapper—and… [sad trombone sound](minetest/minetestmapper#97). :poop:

The problem lay in the following nodes:

* `techage:axle_on`
* `techage:cooler`
* `techage:cooler_on`
* `techage:forceloadtile`
* `techage:gearbox_on`
* `techage:meltingpot_active`
* `techage:oilexplorer_on`
* `techage:ta2_autocrafter_act`
* `techage:ta2_distributor_act`
* `techage:ta2_gravelsieve_act`
* `techage:ta2_grinder_act`
* `techage:ta2_rinser_act`
* `techage:ta3_autocrafter_act`
* `techage:ta3_distributor_act`
* `techage:ta3_gravelsieve_act`
* `techage:ta3_grinder_act`
* `techage:ta3_rinser_act`
* `techage:ta4_autocrafter_act`
* `techage:ta4_collider_cooler`
* `techage:ta4_distributor_act`
* `techage:ta4_gravelsieve_act`
* `techage:ta4_grinder_act`
* `techage:ta4_high_performance_distributor_act`
* `techage:ta4_recycler_act`

Turns out that these nodes all have a tile definition that is a table that does *not* have a `name` field… but instead uses [the deprecated `image` field](https://minetest.gitlab.io/minetest/definition-tables/#tile-definition).

I have already filed [an issue for the mapper utility to prevent the crash](minetest/minetestmapper#97)… but the `image` field is still deprecated, and should probably be changed anyway.

**Comment by joe7575** [comment]
Thanks for the report.
This issue is fixed here: https://github.com/joe7575/techage/commit/b2ad9f3058bd5c8a9fa2572aafebf4f7f01cd42e
I will close this issue with the next update of techage_modpack
