### ISSUE TITLE
"datastorage" lacks a license

### ISSUE THREAD

**Issue by TristanCottam** [joe7575/techage_modepack#14]
The [`joe7575/datastorage`](https://github.com/joe7575/datastorage) mod is forked from [`minetest-technic/datastorage`](https://github.com/minetest-technic/datastorage), which lacks a license. This means the original project preserves all of its rights, including reproduction, distribution, and modification. [An issue was filed for the original project](https://github.com/minetest-technic/datastorage/issues/4), but it remains unanswered almost 3 years later.

Consequently, the `datastorage` mod must either be rewritten from scratch, or removed altogether.

**Comment by joe7575** [comment]
Thanks for the tip, the mod isn't used anyway and will be phased out with the next update.
