### ISSUE TITLE
Tubes are not working as intended

### ISSUE THREAD

**Issue by Alatarius** [joe7575/techage_modepack#16]
When trying to connect a tube it will not connect to the machine at all, also when truing to move things through a tube with the distributor nothing will go through the tubes at all. I think this might have to do with tubelib as it has been deprecated through pipeworks mod. 

[edit] Also tried moving things with a pusher through a tube and that doesn't work either.

**Comment by joe7575** [comment]
You can't mixup pipeworks and techage. Disable pipeworks and test if techage works

**Comment by Alatarius** [comment]
Tried your suggestion problem still exists. Tubes won't connect correctly, and if a tube is connected to a distributor, then items won't co through tube. Distributer only seems to work if a chest only is connected to it. And the gravel washer stopped working after disabling pipeworks. Items stay on top of washer instead of being moved by the water, I started a new world and all the problems still remain.

**Comment by Alatarius** [comment]
This is from my world where only techage is active. No matter what I do, the tubes shown will not connect
![Untitled](https://github.com/joe7575/techage_modpack/assets/101660302/60787d44-ad49-4200-a2b8-01466e5c12ef)

[edit] I made this quickly which is why there is no water. Just demonstrating tube error. This happens trying to connect tubes to anything but other tubes

**Comment by Alatarius** [comment]
I also get the same issue when trying to connect axles.
![Untitled2](https://github.com/joe7575/techage_modpack/assets/101660302/a95b563a-9954-4919-8099-4ac4eaa1f10b)

**Comment by joe7575** [comment]
Pleased check the construction Board. For the washer, the orange Tubes ore wrong.
The black hole in the flywheel hast to show to the cylinder

**Comment by Alatarius** [comment]
> Pleased check the construction Board. For the washer, the orange Tubes ore wrong. The black hole in the flywheel hast to show to the cylinder

The board shows the orange tubes
![Untitled](https://github.com/joe7575/techage_modpack/assets/101660302/da5657e3-78b6-4030-a3b4-0a232370ace5)

**Comment by Alatarius** [comment]
As for the flywheel there is a black hole on both sides of it

**Comment by Alatarius** [comment]
And here is an image with me hovering over the tube icon on the board
![Untitled](https://github.com/joe7575/techage_modpack/assets/101660302/e2219aa4-c7be-48cc-8ba8-c2e96a434a4c)

**Comment by joe7575** [comment]
![screenshot_20230808_202801](https://github.com/joe7575/techage_modpack/assets/17710938/725335b7-365f-4ac1-9de4-29333a1f13fb)
![screenshot_20230808_202806](https://github.com/joe7575/techage_modpack/assets/17710938/e41d866f-90ab-4ae0-a668-cb0149bb7a58)
Did you notice that you used TA2 Steam Pipes instead of tubes?

**Comment by joe7575** [comment]
Here some tips and tricks: https://github.com/joe7575/techage_modpack/blob/master/tips_and_tricks.md

**Comment by Alatarius** [comment]
>Did you notice that you used TA2 Steam Pipes instead of tubes?

That was the problem? I feel all durr now. They look the same to me being visually impaired (not blind). However I reloaded the mod in my world thinking that was the problem now I have a new problem.

Now the wheat mill only spins once and stops. The waterwheel is working fine, It's just the wheat mill that does this. It no longer spins continuously as the waterwheel spins.

Should I move this to a separate issue or just leave it here.
