### ISSUE TITLE
Mill only spins once then stops

### ISSUE THREAD

**Issue by Alatarius** [joe7575/techage_modepack#17]
The Mill when connected to the water wheel only spins once then stops. It does not spin continuously with the waterwheel. Whaterwheel works fine. Mill does not making you have to manually keep it going.
[mill problem.webm](https://github.com/joe7575/techage_modpack/assets/101660302/3b514d7f-270b-43e0-9f16-63401740d749)

**Comment by joe7575** [comment]
Please check the plan, you built it wrong

**Comment by Alatarius** [comment]
Did check the plan, it was working correctly until I reinstalled the mod from github. If I install the older version from ContentDB it works, correctly again.

Also telling me to always check the plan, and I do otherwise I couldn't even attempt to build it, then maybe your plans should make things a little more clear. The video shows everything that the plan does but it wasn't working correctly.

I am now of the opinion that this mod is not for the average user and I have to become some mind reader to understand this. I do read the plans and I still end up building things wrong. Maybe add some real documentation to it. If things need to be in a certain direction (North, South, East, West) then maybe put that in the documentation/plans. They are not very intuitive.

**Comment by Alatarius** [comment]
This is the plans compared to the build. Do thing have to be in a very specific direction?

![mill 01](https://github.com/joe7575/techage_modpack/assets/101660302/0d3e758c-94c3-4d75-bc4d-91794c5dfa10)
![mill 02](https://github.com/joe7575/techage_modpack/assets/101660302/79b181f3-cdb4-478d-8a8b-b78698a9dd0f)

**Comment by Alatarius** [comment]
This is the plans compared to the build. Do thing have to be in a very specific direction?
![mill 01](https://github.com/joe7575/techage_modpack/assets/101660302/002b0b38-5ff6-46cd-ac8f-404fd70c0507)
![mill 02](https://github.com/joe7575/techage_modpack/assets/101660302/07a10e32-f2d4-443c-bf46-80f625f5484c)

**Comment by joe7575** [comment]
![mill3](https://github.com/joe7575/techage_modpack/assets/17710938/878142d4-a273-4c75-8778-aaef66bed45d)
![mill2](https://github.com/joe7575/techage_modpack/assets/17710938/e4d0c8fb-7015-4cd2-b867-94dc3e4942f5)
![mill1](https://github.com/joe7575/techage_modpack/assets/17710938/12d5a3fd-1fcd-4c69-9d08-febb13e131f2)

Do you see the differences?
