### ISSUE TITLE
Crash when resuming game (just after load) -- Solutions

### ISSUE THREAD

**Issue by gd2shoe** [joe7575/techage_modepack#20]
```
2023-10-19 11:04:07: ERROR[Main]: ServerError: AsyncErr: Lua: Runtime error from mod 'techage' in callback node_on_timer(): ...echage_modpack\techage/coal_power_station/oilfirebox.lua:42: attempt to perform arithmetic on a boolean value
2023-10-19 11:04:07: ERROR[Main]: stack traceback:
2023-10-19 11:04:07: ERROR[Main]:       ...echage_modpack\techage/coal_power_station/oilfirebox.lua:42: in function <...echage_modpack\techage/coal_power_station/oilfirebox.lua:28>
```

The boolean in question turns out to be fuel.burntime(liq_name), which comes from techage.firebox.Burntime, which comes from firebox_lib.lua:

```
techage.firebox.Burntime = {
	["techage:charcoal"] = true, -- will be replaced by burntime
	["default:coal_lump"] = true,
	["default:coalblock"] = true,
	["techage:oil_source"] = true,
	["techage:gas"] = true,
	["techage:gasoline"] = true,
	["techage:naphtha"] = true,
	["techage:fueloil"] = true,
}
```

And here's the culprit:

`minetest.after(1, determine_burntimes)`

This is a race condition.  It probably doesn't happen very often.  The node_on_timer callback gets triggered within the first second that the server is online, and during that second, the array isn't properly initialized.

This problem has 2 solutions, I suggest both of them.  The initial value should be numerical, not boolean.  Changing those 'true' into '1' would give the wrong answer to burntimes, but it would stop the crash.  Second, I suggest replacing the minetest.after with register_on_mods_loaded.  That's what this line is trying to do anyway.

`minetest.register_on_mods_loaded(determine_burntimes)`

**Comment by joe7575** [comment]
Thank you for the report. Very good work and report.  I recently solved this exact error: 
https://github.com/joe7575/techage/commit/1838507521d909016b7e55f94f03e35d83fba361

Unfortunately, this is currently only available directly in the Techage Mod.
I will update the `techage_modpack` again soon. 
In the meantime, please use the code from (here)[https://github.com/joe7575/techage].
