### ISSUE TITLE
gives an error message

### ISSUE THREAD

**Issue by VinAdmin** [joe7575/techage_modepack#22]
2024-02-24 15:21:59: ERROR[Main]: ServerError: AsyncErr: Lua: Runtime error from mod 'techage' in callback node_on_timer(): .../../mods/techage_modpack/techage/lamps/growlight.lua:78: bad argument #2 to 'random' (interval is empty)
2024-02-24 15:21:59: ERROR[Main]: stack traceback:
2024-02-24 15:21:59: ERROR[Main]:       [C]: ?
2024-02-24 15:21:59: ERROR[Main]:       [C]: in function 'random'
2024-02-24 15:21:59: ERROR[Main]:       .../../mods/techage_modpack/techage/lamps/growlight.lua:78: in function 'grow_flowers'
2024-02-24 15:21:59: ERROR[Main]:       .../../mods/techage_modpack/techage/lamps/growlight.lua:97: in function <.../../mods/techage_modpack/techage/lamps/growlight.lua:96>

**Comment by joe7575** [comment]
The bug is fixed here: https://github.com/joe7575/techage/tree/master

Update your mod folder directly from there.
However, you will not have fun with the growlight, if no flowers are registered (this was the reason for the crash)). What kind of game/mods do you use?

**Comment by VinAdmin** [comment]
Thanks for the answer.

We use the game on our server: minetest_game
Mods: 3d_armor, 3d_armor_ip, 3d_armor_sfinv, 3d_armor_stand, 3d_armor_ui, addons_animalworld, advtrains, advtrains_assets, advtrains_interlocking, advtrains_itrainmap, advtrains_line_automation, advtrains_luaautomation, advtrains_signals_ks, advtrains_train _industrial, advtrains_train_japan, advtrains_train_steam, advtrains_train_subway, advtrains_train_track, animalworld, anvil, areas, areas_limit, armor_admin, armor_bronze, armor_cactus, armor_crystal, armor_diamond, armor_gold, armor_mithril, armor_nether, armor_steel, armor_wood, artdeco, artdeco_recipes, atm, autobahn, awards, basic_materials, bbq, beds, beowulf, betterpm, binoculars, boards, boats, bonemeal, bones, bucket, butterflies, Carts, Chatlogger, Choppy, Cleaner, Coloredglass, Coloredobsidian, ColoredStone, ColoredStonebrics, Coloredwoodplank, Compost, Connected_chests, Craft_ings VE, Currency, Death_compass, Decor_api, Default, Digilines, Digilines_commandblock, Digilines_entity_detector, Digilines_Player_Detector, Digistuff, Digtr on, discordmt, display_api, doc, doc_encyclopedia, doc_identifier, doc_items, doclib, doors, drawers, dropitem_command, dumpnodes, dungeon_loot, dye, env_sounds, ethereal, farming, filter, fire, fireflies, fireworks_redo, flowers, fmod, font_api, font_metro, futil, game_commands, give_initial_stuff, glass_stained, headanimoptimized, hotbar_16, hyperloop, interact, itemframes, j_mute, jail, jonez, keys, lcdlib, led_marquee, living_trees, livingnether, map, mapserver, mesecons, mesecons_alias, mesecons_blinkyplant, mesecons_button, mesecons_commandblock, mesecons_delayer, mesecons_detector, mesecons_ doors, mesecons_extrawires, mesecons_fpga, mesecons_gamecompat, mesecons_gates, mesecons_hydroturbine, mesecons_insulated, mesecons_lamp, mesecons_lightstone, mesecons_luacontroller, mesecons_luacontroller_term, mesecons_materials, mesecons_microcontroller, mesecons_movestones, mesecons_mvps, mesecons_noteblock, mesecons_powerplant, mesecons_ pressure plates, meseco

If interested, I can give you the server address.
