### ISSUE TITLE
coal tower

### ISSUE THREAD

**Issue by TheFelin** [joe7575/techage_modepack#23]
We can no longer light the coal tower with the straw?

**Comment by joe7575** [comment]
A lighter has always been necessary for this.
See: [wiki](https://github.com/joe7575/techage/blob/master/manuals/manual_ta1_EN.md#melting-furnace)

**Comment by TheFelin** [comment]
We can't figure it out, it works before the last update, can you take a look? our server minetest.clododunet.com
THANKS

**Comment by TheFelin** [comment]
we found the problem, it seems that a mod is preventing the tower from working, we are looking for it...

**Comment by joe7575** [comment]
OK, thanks. I close this issue
