### ISSUE TITLE
Energy Storage respawn red gravel infinit

### ISSUE THREAD

**Issue by Pez4** [joe7575/techage_modepack#24]
I'm playing on the Archtec server and the Niklp admin asked me to tell you about my problem. Once my energy storage (9x9) is completely installed and connected on the electrical side, if I remove the blocks where the window is located to see the gravel block either grey or red depending on the energy percentage, at the block location there will always be a block that will reappear endlessly every 5 seconds. Maybe it's the heatexchanger that creates the node?

**Comment by joe7575** [comment]
Thanks for the report. The bug is fixed [here](https://github.com/joe7575/techage/commit/0b50136116036940eb5ca2025b9801fdd46dbefc)
