### ISSUE TITLE
Unified inventory from the modpack is outdated

### ISSUE THREAD

**Issue by Lesya-cpp** [joe7575/techage_modepack#5]
Mod Unified Inventory from techage_modpack has old version that is no longer compatible with mods like '3D Armor' or 'skinsdb'. Trying to disable Unified Inventory leads some machines (for example TA1 mill) to stop processing any items. Please update Unified Inventory.
OS: Arch Linus
Minetest version: 5.4.1 (from repo)

**Comment by joe7575** [comment]
Should be fixed now
